### PR TITLE
Update the wasm encoder to the 0xb format

### PR DESCRIPTION
**Pull request by binji**
- Expression encoding is now post-order instead of pre-order
- There is a new `end` opcode, used instead of explicitly specifying the
  number of expressions in `block` and `loop`
- the `if` opcode now introduces a new label scope for the true and
  false branches.
- Some opcodes moved around (`return`, `unreachable`, etc.)
- `br`, `br_if`, `return` and `call*` all have an explicit arity (i.e.
  number of arguments)
- Section names are shortened (e.g. "function_signatures" -> "function")

### CODE REVIEW

**Comment by binji** [comment]
I didn't actually test this in the browser, but I have tried decoding it and it seems OK.

**Comment by evanw** [comment]
Thanks for looking at updating this! Unfortunately, your patch doesn't work. Running in Chrome Canary gives `Uncaught WasmModule::Instantiate(): Compiling WASM function #15:ByteArray_set16 failed:Result = arity mismatch in direct function call (expected 3, got 2) @+11`.

**Comment by binji** [comment]
Ah, I wasn't including the implicit `this` argument in the arity. I don't have a recent enough Chrome available to test, but it loads in command-line v8 now.

**Comment by binji** [comment]
Closing -- version 0xb is ancient at this point, and @dcodeIO has updated to version 1 here: https://github.com/evanw/thinscript/issues/16.

**Pull request closed without merging**
